/**
 * Clowder Build Phase Orchestrator.
 *
 * When the user triggers "force start" or all experts reach sufficient confidence,
 * this orchestrator:
 * 1. Synthesizes the planning artifacts (spec, backlog, arch doc, data model)
 * 2. Saves them to Org Vault via the platform API
 * 3. (v1 stub) Marks experts as "building" and the session as "building"
 * 4. (v2) Creates KAIT sessions per expert and monitors build progress
 *
 * V1 is intentionally stubbed for the build phase execution.
 * V2 will wire KAIT sessions to each expert.
 */

import { execSync } from "child_process";
import {
  getClowderSession,
  listClowderExperts,
  listClowderMessages,
  sendClowderMessage,
  updateClowderExpert,
  getApiBaseUrl,
  buildHeaders,
} from "./api.server";

interface BuildArtifact {
  type: "spec" | "backlog" | "architecture" | "data_model";
  title: string;
  content: string;
}

/**
 * Generate planning artifacts using Claude headless.
 * Falls back to stub content if Claude is not available.
 */
async function generatePlanningArtifacts(
  sessionDescription: string,
  messages: Array<{ role: string; content: string }>
): Promise<BuildArtifact[]> {
  const conversationSummary = messages
    .slice(-20)
    .map((m) => `${m.role}: ${m.content}`)
    .join("\n");

  const prompt = `Based on this app idea and expert discussion, generate a planning document.

App Idea: ${sessionDescription}

Expert Discussion:
${conversationSummary}

Generate a comprehensive spec in markdown. Include:
1. App overview and value proposition
2. Target users
3. Core features (MVP)
4. User flows
5. Data model (entities and relationships)
6. Technical architecture
7. Implementation backlog (10-15 prioritized stories)

Output only the markdown document, no preamble.`;

  try {
    const spec = execSync(`claude --dangerously-skip-permissions`, {
      input: prompt,
      encoding: "utf8",
      timeout: 120000,
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();

    if (spec.length > 100) {
      return [
        {
          type: "spec",
          title: "App Specification",
          content: spec,
        },
      ];
    }
  } catch {
    // Fall through to stub
  }

  // Stub artifacts — used when Claude is not available
  return [
    {
      type: "spec",
      title: "App Specification",
      content: `# App Specification

## Overview
${sessionDescription}

## Status
Planning artifacts will be generated by the expert committee during the build phase.

## Next Steps
- Expert committee to finalize requirements
- Architecture review
- Implementation kickoff
`,
    },
    {
      type: "backlog",
      title: "Implementation Backlog",
      content: `# Implementation Backlog

## Epic 1: Core Infrastructure
- [ ] Project setup and scaffolding
- [ ] Database schema implementation
- [ ] Authentication system
- [ ] API layer

## Epic 2: Core Features
- [ ] Primary user flow
- [ ] Data management UI
- [ ] User account management

## Epic 3: Polish
- [ ] Responsive design
- [ ] Error handling
- [ ] Performance optimization
- [ ] Documentation
`,
    },
  ];
}

/**
 * Save artifacts to Org Vault via the platform API.
 */
async function saveArtifactsToVault(
  orgId: string,
  sessionName: string,
  artifacts: BuildArtifact[]
): Promise<void> {
  for (const artifact of artifacts) {
    const path = `apps/${sessionName.toLowerCase().replace(/\s+/g, "-")}/${artifact.type}.md`;

    try {
      await fetch(`${getApiBaseUrl()}/v1/vault/files/${encodeURIComponent(path)}`, {
        method: "PUT",
        headers: buildHeaders(),
        body: JSON.stringify({
          content: artifact.content,
          message: `Clowder: Add ${artifact.title}`,
          org_id: orgId,
        }),
      });
    } catch (e) {
      console.error(`Failed to save artifact ${path}:`, e);
      // Non-fatal — continue with other artifacts
    }
  }
}

/**
 * Run the build phase for a session.
 *
 * V1: Generates artifacts, saves to vault, marks session as "building".
 * V2: Will spawn KAIT sessions per expert for actual implementation.
 */
export async function runBuildPhase(sessionId: string): Promise<void> {
  const { session } = await getClowderSession(sessionId);
  const [experts, messages] = await Promise.all([
    listClowderExperts(sessionId),
    listClowderMessages(sessionId),
  ]);

  // Update session to planning phase
  await sendClowderMessage(sessionId, {
    content: "Great — I have enough to work with. Let me synthesize what we've discussed and create your app plan.",
    role: "system",
    metadata: { phase: "planning" },
  });

  // Generate artifacts
  const artifacts = await generatePlanningArtifacts(
    session.description ?? "",
    messages.map((m) => ({ role: m.role, content: m.content }))
  );

  // Save artifacts to platform (Clowder artifacts table)
  for (const artifact of artifacts) {
    try {
      await fetch(`${getApiBaseUrl()}/v1/clowder/sessions/${sessionId}/artifacts`, {
        method: "POST",
        headers: buildHeaders(),
        body: JSON.stringify({
          artifact_type: artifact.type === "spec" ? "spec" : artifact.type,
          title: artifact.title,
          content: artifact.content,
          created_by: "po",
        }),
      });
    } catch (e) {
      console.error("Failed to save artifact:", e);
    }
  }

  // Also try vault (non-fatal)
  await saveArtifactsToVault(session.org_id, session.name, artifacts).catch(() => {});

  // Mark all experts as "building"
  for (const expert of experts) {
    await updateClowderExpert(sessionId, expert.id, {
      status: "building",
      confidence: 1.0,
    }).catch(() => {});
  }

  // System message: building started
  await sendClowderMessage(sessionId, {
    content: `Planning complete! I've generated your app specification and backlog.

**What was created:**
${artifacts.map((a) => `- ${a.title}`).join("\n")}

In v2, the expert committee would now spawn dedicated build sessions and implement your app autonomously. For now, your planning documents are ready to review and hand to a developer.

Your app plan has been saved to your Org Vault.`,
    role: "system",
    metadata: { phase: "building", artifacts_count: artifacts.length },
  });
}
